# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 852a84fd7acc5658070e6a689a0679389735115a5aeaa27064db0ddc77e16a59f24ea0926f06a0f859fb6a429272471ceca8331e1ebd497758bee9f179b868aa

test:
  secret_key_base: 604d43bcf169568e0c867fddde63030aab705179ff515d32e572e741053042512e1c5cb6444a19887488110121cc747e2e092e383fcd31683fb93b16f8d34b1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
